TruthSet Match Position

In [196]:
import numpy as np
import pandas as pd
import os
from tqdm import tqdm 
from os import listdir
import pdb
from multiprocessing.pool import Pool

In [214]:
#test_split = "/mnt/berk/samples_new/"
target_list_path = "~/Desktop/ECOLE/ECOLE-main/hglft_genome_64dc_dcbaa0.bed"
#cnvnator_wgs_calls_path = "/mnt/furkan/CNVNATOR_WGS_DATA/"
sample_name="normal.10x_LR-shortDels.IL_N_1"
target_data = pd.read_csv(target_list_path, sep="\t", header=None).values

In [208]:
wgs_ends_list = []
wgs_start_list = []
chr_list = []
sv_label_list = []
wgs_calls_data = pd.read_csv(sample_name+".vcf", sep="\t",comment='#',header=None).values
wgs_ends_list_tmp = [x.split(";") for x in wgs_calls_data[:,7]]
for ind,iterlist in enumerate(wgs_ends_list_tmp) :
    start_loc = wgs_calls_data[ind][1]
    chr = wgs_calls_data[ind][0]
    for  i in  iterlist:
        if(i[:4]=="END="):
            wgs_start_list.append(start_loc)
            wgs_ends_list.append(int(i.split("=")[1]))
            chr_list.append(chr)
            sv_label_list.append(wgs_calls_data[ind,7].split(";")[0].partition("=")[2])
wgs_start_list = np.asarray(wgs_start_list)
wgs_ends_list = np.asarray(wgs_ends_list)
chr_list = np.asarray(chr_list)
sv_label_list = np.asarray(sv_label_list)




In [219]:
#For normal.10x_LR-shortDels.IL_N_1
wgs_ends_list = []
wgs_start_list = []
chr_list = []
sv_label_list = []
wgs_calls_data = pd.read_csv(sample_name+".vcf", sep="\t",comment='#',header=None).values
wgs_ends_list_tmp = [x.split(";") for x in wgs_calls_data[:,7]]
for ind,iterlist in enumerate(wgs_ends_list_tmp) :
    start_loc = wgs_calls_data[ind][1]
    chr = wgs_calls_data[ind][0]
    for  i in  iterlist:
        if(i[:4]=="END="):
            wgs_start_list.append(start_loc)
            wgs_ends_list.append(int(i.split("=")[1]))
            chr_list.append(chr)
            sv_label_list.append(wgs_calls_data[ind,4])
wgs_start_list = np.asarray(wgs_start_list)
wgs_ends_list = np.asarray(wgs_ends_list)
chr_list = np.asarray(chr_list)
sv_label_list = np.asarray(sv_label_list)


In [209]:
#For Sniffeer
for i in tqdm(range(target_data.shape[0])):
#get the chracter, start and end indices in the target
    target_chr = target_data[i,0]
    target_st = int(target_data[i,1])
    target_end = int(target_data[i,2])

    appropriate_inds_wgscalls =   (wgs_start_list < target_st) * ( wgs_ends_list > target_end) * (target_chr == chr_list)



    groundtruthcall = ""
    if np.sum(appropriate_inds_wgscalls) == 0:
        #no call
        groundtruthcall = "<NO-CALL>"
    else:
        #print('here wgs',wgs_calls_data[appropriate_inds_wgscalls,4])
        groundtruthcall =  wgs_calls_data[appropriate_inds_wgscalls,4][0]
        
    os.makedirs(os.path.dirname("./Groundtruth_" + sample_name + ".csv"), exist_ok=True)

    f = open("./Groundtruth_" + sample_name + ".csv", "a")
        
        
            
    f.write(target_chr + "," +str(target_st) + ","+str(target_end) + ","+groundtruthcall+"\n")

  4%|▍         | 8519/193241 [00:00<00:13, 13439.08it/s]


IndexError: boolean index did not match indexed array along dimension 0; dimension is 4446 but corresponding boolean dimension is 4406

In [220]:
#For normal.PB.pbsv.vcf.gz   
for i in tqdm(range(target_data.shape[0])):
#get the chracter, start and end indices in the target
    target_chr = target_data[i,0]
    target_st = int(target_data[i,1])
    target_end = int(target_data[i,2])

    appropriate_inds_wgscalls =   (wgs_start_list < target_st) * ( wgs_ends_list > target_end) * (target_chr == chr_list)



    groundtruthcall = ""
    if np.sum(appropriate_inds_wgscalls) == 0:
        #no call
        groundtruthcall = "<NO-CALL>"
    else:
        #print('here wgs',wgs_calls_data[appropriate_inds_wgscalls,4])
        groundtruthcall =  "<"+sv_label_list[appropriate_inds_wgscalls][0]+">"
        
    os.makedirs(os.path.dirname("./Groundtruth_" + sample_name + ".csv"), exist_ok=True)

    f = open("./Groundtruth_" + sample_name + ".csv", "a")
        
        
            
    f.write(target_chr + "," +str(target_st) + ","+str(target_end) + ","+groundtruthcall+"\n")

100%|██████████| 193241/193241 [00:14<00:00, 13088.53it/s]


In [222]:
#For normal.10x_LR-shortDels.IL_N_1 
for i in tqdm(range(target_data.shape[0])):
#get the chracter, start and end indices in the target
    target_chr = target_data[i,0]
    target_st = int(target_data[i,1])
    target_end = int(target_data[i,2])

    appropriate_inds_wgscalls =   (wgs_start_list < target_st) * ( wgs_ends_list > target_end) * (target_chr == chr_list)



    groundtruthcall = ""
    if np.sum(appropriate_inds_wgscalls) == 0:
        #no call
        groundtruthcall = "<NO-CALL>"
    else:
        #print('here wgs',wgs_calls_data[appropriate_inds_wgscalls,4])
        groundtruthcall =  sv_label_list[appropriate_inds_wgscalls][0]
        
    os.makedirs(os.path.dirname("./Groundtruth_" + sample_name + ".csv"), exist_ok=True)

    f = open("./Groundtruth_" + sample_name + ".csv", "a")
        
        
            
    f.write(target_chr + "," +str(target_st) + ","+str(target_end) + ","+groundtruthcall+"\n")

100%|██████████| 193241/193241 [00:14<00:00, 13011.47it/s]


In [177]:
sv_label_list[appropriate_inds_wgscalls]

array([], dtype='<U3')

In [189]:
np.any(sv_label_list=="DUP")

False

In [234]:
import numpy as np
from sklearn.metrics import confusion_matrix as cm
import os
from tqdm import tqdm
import pandas as pd


preds_ = np.array([])
wgs_preds_ = np.array([])


    
ecole_calls_data = pd.read_csv("~/Desktop/ECOLE/Revision/Analysis/Task3/Normal_WES/ecole_calls_output/WES_IL_N_1_v3.csv", sep="\t",header=None)
wgs_calls_data = pd.read_csv("~/Desktop/ECOLE/Revision/Analysis/Task3/Normal_SNV_GroundTruth/Groundtruth_normal.PB.pbsv.csv", sep=",",header=None)
ecole_calls_data = ecole_calls_data[1:][[1,2,3,4]]
ecole_calls_data = ecole_calls_data.T.reset_index(drop=True).T
ecole_calls_data[1]=ecole_calls_data[1].astype(int)
ecole_calls_data[2]=ecole_calls_data[2].astype(int)


new_df = pd.merge(wgs_calls_data, ecole_calls_data,  how='left', left_on=[0,1,2], right_on = [0,1,2]).values

wgs_preds_n = np.array(new_df[:,3]) 
wgs_preds_ = np.append(wgs_preds_,wgs_preds_n)
preds_n= np.array(new_df[:,4]) 
preds_ = np.append(preds_,preds_n)
        
wgs_preds_[wgs_preds_ == "<DEL>"] = 2
wgs_preds_[wgs_preds_ == "<DUP>"] = 1
wgs_preds_[(wgs_preds_!=2) * (wgs_preds_!=1)] = 0
wgs_preds_ = wgs_preds_.astype(int)


delcalls = wgs_preds_ == 2
dupcalls = wgs_preds_ == 1
nocallcalls = wgs_preds_ == 0


preds_[preds_ == "DEL"] = 2
preds_[preds_ == "DUP"] = 1
preds_[(preds_!=2) * (preds_!=1)] = 0
preds_ = preds_.astype(int)

preds_ = preds_.astype(int)

delpreds_ = preds_ == 2
duppreds_  = preds_ == 1
nocallpreds_  = preds_ == 0



delrecall_  = np.sum(delpreds_ * delcalls) / np.sum(delcalls)
duprecall_  = np.sum(duppreds_  * dupcalls) / np.sum(dupcalls)
print("deletion recall:", delrecall_)
print("duplication recall:", duprecall_)

delprec_  = np.sum(delpreds_  * delcalls) / np.sum(delpreds_ )
dupprec_  = np.sum(duppreds_  * dupcalls) / np.sum(duppreds_ )
print("deletion precision:", delprec_)
print("duplication precision: ",dupprec_ )

print("confusion matrix: \n",cm(wgs_preds_, preds_))

/tmp/ipykernel_11377/2967436449.py:13: DtypeWarning: Columns (2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  ecole_calls_data = pd.read_csv("~/Desktop/ECOLE/Revision/Analysis/Task3/Normal_WES/ecole_calls_output/WES_IL_N_1_v3.csv", sep="\t",header=None)


deletion recall: 0.4935064935064935
duplication recall: nan
deletion precision: 0.013080895008605853
duplication precision:  0.0
confusion matrix: 
 [[190766    455   2867]
 [     0      0      0]
 [    39      0     38]]


/tmp/ipykernel_11377/2967436449.py:53: RuntimeWarning: invalid value encountered in scalar divide
  duprecall_  = np.sum(duppreds_  * dupcalls) / np.sum(dupcalls)


In [204]:
np.sum(delpreds_ )

2905